worker_processes 1;
events {
    worker_connections 1024;
}

http {
    server_tokens off; #to hide server details
    include mime.types;
    
    upstream nodejs_cluster {
        least_conn;
        server localhost:3001;
        server localhost:3002;
        server localhost:3003;
    }

    server {
        listen 443 ssl; #PORT changed from 8085 to 443 because SSL was implemented
        server_name localhost; #if this was production, localhost would change to the site url

        ssl_certificate /etc/ssl/certs/cert.crt;
        ssl_certificate_key /etc/ssl/private/privkey.key;

        location / {
            proxy_pass http://nodejs_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}